dataset:
  name: color_mnist
  img_size: 28
  batch_size: 64
  test_batch_size: 1000
  num_channels: 3
model:
  type: cb_vaegan
  latent_noise_dim: 64
  input_latent_dim: 10
  pre_concept_latent_dim: 124
  pre_concept_layers: 5
  has_concepts: True
  concepts: 
      emb_size: 16
      concept_names: ["label","red","green"]
      types: ["cat", "bin","bin" ]
      concept_latent: [10,10,10]
      concept_hidden: [124,124,124]
      concept_bins: [10,2,2]
      concept_output: [10,1,1]

train_config:
  epochs: 20
  gen_lr: 0.005
  dis_lr: 0.0001
  rec_lr: 0.001
  betas: (0.5, 0.99)
  save_model: True
  use_cuda: True
  log_interval: 100
  plot_loss: True
evaluation:
  generation: True
  save_images: True
  save_concept_image: True
  score_concepts: True
  save_results: True