dataset:
  name: celeba
  transforms_1: (0.5)
  transforms_2: (0.5)
  img_size: 64
  batch_size: 32
  test_batch_size: 1000
  num_channels: 3
  num_concepts: 8
model:
  type: vaegan
  latent_noise_dim: 100 
  input_latent_dim: None
  has_concepts: False
train_config:
  epochs: 50
  gen_lr: 0.002
  dis_lr: 0.0002
  betas: (0.5, 0.999)
  save_model: True
  use_cuda: True
  log_interval: 100
  plot_loss: True
evaluation:
  generation: True
  save_images: True
  save_results: True